export const annotateRegion = (region: string): string => {
  const annotations: Record<string, string> = {
    Karelia: "Karelia",
    Moscow: "Mosc.",
    "Saint Petersburg": "St.P",
    "Novosibirsk Oblast": "Novo.",
    "Krasnoyarsk Krai": "KRNY",
    "Krasnodar Krai": "KRND",
    "Nizhny Novgorod Oblast": "NN",
    "Yaroslavl Oblast": "Yaros.",
    "Chelyabinsk Oblast": "Chel.",
    "Khabarovsk Krai": "Khabarovsk",
    "St. Petersburg": "StP",
    Buryatia: "Buryatia",
    "Ryazan Oblast": "Ryazan",
    "Magadan Oblast": "Magadan",
    Tuva: "Tuva",
    "Smolensk Oblast": "Smolensk",
    "Arkhangelsk Oblast": "Arkh",
    "Altai Krai": "Altai",
    "Karachay-Cherkessia": "K-Ch",
    "Lipetsk Oblast": "Lipetsk",
    "Tambov Oblast": "Tambov",
    "Leningrad Oblast": "Len.",
    Kalmykia: "Kalmykia",
    "Moscow Oblast": "Mosc.",
    "Oryol Oblast": "Oryol",
    "Belgorod Oblast": "Bel.",
    "Kaliningrad Oblast": "Kal.",
    "Voronezh Oblast": "Voro.",
    "Rostov Oblast": "Rostov",
    "Stavropol Krai": "Stav.",
    "Perm Krai": "Perm",
    "Altai Republic": "Altai",
    "Bryansk Oblast": "Bryansk",
    Mordovia: "Mordovia",
    Bashkortostan: "Bashk.",
    "Kostroma Oblast": "Kost.",
    "Khanty-Mansi Autonomous Okrug": "Khanty",
    Udmurtia: "Udmurtia",
    Tatarstan: "Tatarstan",
    "Tyumen Oblast": "Tyumen",
    "Ulyanovsk Oblast": "Ulyanovsk",
    "Jewish Autonomous Oblast": "JAO",
    "Samara Oblast": "Samara",
    "Ivanovo Oblast": "Ivanovo",
    "Yamalo-Nenets Autonomous Okrug": "Yamalo.",
    "Kabardino-Balkaria": "Kab.",
    "Primorsky Krai": "Primorsky",
    "Penza Oblast": "Penza",
    "North Ossetia-Alania": "N.O.",
    "Murmansk Oblast": "Murm.",
    "Omsk Oblast": "Omsk",
    "Kursk Oblast": "Kursk",
    "Kurgan Oblast": "Kurgan",
    "Tula Oblast": "Tula",
    "Tomsk Oblast": "Tomsk",
    Khakassia: "Khakassia",
    "Kaluga Oblast": "Kaluga",
    "Amur Oblast": "Amur",
    "Novgorod Oblast": "Novg.",
    Chuvashia: "Chuvashia",
    "Sverdlovsk Oblast": "Sver",
    "Vologda Oblast": "Vologda",
    "Nenets Autonomous Okrug": "Nenets",
    "Kemerovo Oblast": "Keme.",
    "Orenburg Oblast": "Oren.",
    "Irkutsk Oblast": "Irkutsk",
    "Kirov Oblast": "Kirov",
    "Vladimir Oblast": "Vladimir",
    Chechnya: "Chechnya",
    "Zabaykalsky Krai": "Zaba.",
    "Kamchatka Krai": "KCHTK",
    "Sakhalin Oblast": "SAK",
    Uppland: "Uppl.",
    Skane: "Sk.",
    Vastergotland: "Västg.",
    Narke: "Närke",
    Vastmanland: "Väst.",
    Smaland: "Smål.",
    Vasterbotten: "Västerb.",
    Orebro: "Öreb.",
    Angermanland: "Ångerl.",
    Bohuslan: "Bohusl.",
    Jamtland: "Jämtl.",
    Blekinge: "Blek.",
    Sodermanland: "Söder.",
    Medelpad: "Medelp.",
    Ostergotland: "Östg.",
    Gastrikland: "Gästr.",
    Dalarna: "Dal.",
    Norrbotten: "Norrb.",
    Lappland: "Lappl.",
    Harjedalen: "Härj.",
    Varmland: "Värml.",
    Halland: "Hall.",
    Oland: "Öl.",
    Halsingland: "Häls.",
    Gotland: "Gotl.",
    Dalsland: "Dalsl.",
  };
  return annotations[region] || region;
};

export const annotateCountry = (country: string): string => {
  const annotations: Record<string, string> = {
    "Czech Republic": "Czechia",
    Netherlands: "Neth.",
  };
  return annotations[country] || country;
};
